# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d14367d8f0809ddb428364afbd0f1b27c7964ec7398aab3851f79ff9d74d08192eff1cd52b57e4878a57e654b02f24bd55a79e6454217308f33c0764a0cf5c

test:
  secret_key_base: 97ee64dffe2e9cef3e899cf42a868119854c6fdb027a61674efe927fe640b5a2de4b8af8e80508a1ccc7d41b42120d077b82096dea7b3a6b8eb741bd5363f135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
